version: "3.8"
services:
  
  web:
    build: ./front-end
    depends_on:
      - api
      - postgres
    container_name: front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_API=http://localhost:3001
    networks:
      - network-backend
  api:
    build: ./back-end
    depends_on:
      postgres:
         condition: service_started
    container_name: back
    restart: always
    ports:
      - "3001:3001"
    #command: npx prisma migrate deploy && npm devStart
    environment:
       DATABASE_URL: postgresql://user:pass@postgres:5432/db?connect_timeout=1000

       SECRET_KEY: Bco2mYFjYclGvmOYTYyxPXzU4GQuK=8hrt23Ryp45ispU0W9xDx3cbtJiJjGw6Tf1GPU-oWA0v2FWT4xV15u23UzK4VNRwU!iQqz92M-DvRHdsVRKSh6sPiyfLGVV5De2qIpHNTbAuuf52F-49k3IHx99KwTPWCb6VFoaMu!RJT4-u3CU4Zi-=FcAcbiIxIrLi8A=pf9CFcSCIXtiaJp!h21VwW?wTE0EZrwuSXeH3O7?TjnisCpRe?AE

    networks: 
     - network-backend
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
       - 5432:5432
    networks: 
     - network-backend
  
  

networks:
  network-backend:

volumes: 
  postgres: