-- AlterTable
ALTER TABLE "admin" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "election" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "voter" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
